[package]
name = "image_viewer"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/image_viewer.rs"
doctest = false

[dependencies]
anyhow.workspace = true
db.workspace = true
editor.workspace = true
file_icons.workspace = true
gpui.workspace = true
project.workspace = true
settings.workspace = true
theme.workspace = true
ui.workspace = true
util.workspace = true
image.workspace = true
workspace.workspace = true
fs.workspace = true
schemars.workspace = true
serde.workspace = true
serde_derive.workspace = true

[features]
test-support = ["gpui/test-support"]

# [package.metadata.cargo-machete]
# ignored = ["fs", "serde_derive", "image"]
